### ISSUE TITLE
Crashes when the Test are Run

### ISSUE THREAD

**Issue by azamsharp** [Tyler-Keith-Thompson/CucumberSwift#13]
Running the following test crashes all the time: 

```
//
//  WeatherCucumberSwiftTests.swift
//  WeatherCucumberSwiftTests
//
//  Created by Mohammad Azam on 4/13/20.
//  Copyright © 2020 Mohammad Azam. All rights reserved.
//

import XCTest
import UIUTest
import CucumberSwift

@testable import WeatherCucumberSwift

class Findme {}

extension Cucumber: StepImplementation {
   
    public var bundle: Bundle {
        return Bundle(for: Findme.self)
    }
    
    
    public func setupSteps() {
        
        Given("I have a very cool app") { (matches, _) in
            print(matches)
        }
        
        When("I type my name in the name text field") { (matches, _) in
                print(matches)

        }
        
        Then("I should see my name displayed in a label ") { (matches, _) in
                print(matches)

        }
        
    }
    
}

```

<img width="740" alt="Screen Shot 2020-04-13 at 3 27 52 PM" src="https://user-images.githubusercontent.com/16604/79158124-679d8200-7d9b-11ea-8e6b-b474d6e5c0c2.png">

**Comment by Tyler-Keith-Thompson** [comment]
Yikes! You've run into a few problems today, sorry about that.

Can you share with me your version of xcode?
Is this in a UI testing bundle?
Do you have it trying to parallelize test execution?

**Comment by azamsharp** [comment]
Version 11.4 (11E146)
I tried in UI and I tried in normal Testing bundle same result. 
Do you have it trying to parallelize test execution? NO

**Comment by azamsharp** [comment]
I have WeatherValidSearch.feature file inside Features folder. Here is the code: 

```
Feature: Some terse yet descriptive text of what is desired
    
Background:
    Given I am logged in

Scenario Outline: <user> logs in # 1st: Dave, 2nd: Bob
    Given a user named <user> # 1st: Dave, 2nd: Bob
        And a password <password> # 1st: hello, 2nd: *%&#*#!!
    When <user> logs in # 1st: Dave, 2nd: Bob
    Then <user> sees an account balance of: <account balance> # 1st: $0, 2nd: $20,000

    Examples:
        | user  | password | account balance |
        | Dave  | hello    | $0              |
        | Bob   | *%&#*#!! | $20,000         |

```

I have WeatherCucumberSwiftUITests.swift file: 

```
import CucumberSwift
import XCTest

class Findme {}

extension Cucumber: StepImplementation {
    
    public var bundle: Bundle {
        return Bundle(for: Findme.self)
    }
    
    public func setupSteps() {
        
       var username:String?
       var password:String?
       //in case you're not regex savvy (.*?) simply matches 0 or more characters, so it'd grab "Dave" in this step the first time and "Bob" the second time
       Given("^A user named (.*?)$") { (matches, _) in
           username = matches[1] //1st: Dave, 2nd: Bob
       }
       And("^A password (.*?)$") { (matches, _) in
           password = matches[1]
       }
       When("^(.*?) logs in$") { (matches, _) in
           guard let username = username, let password = password else {
               XCTFail("Need a username and password")
                return
           }
         //  findOrCreateAccount(username)
         //  login(username: username, password: password)
       }
       Then("^(.*?) sees an account balance of: (.*?)$") { (matches, _) in
           let username = matches[1]
           let balance = matches[2]
            XCTAssertEqual(1, 2)
         //  XCTAssertEqual(nameLabel.text, username)
         //  XCTAssertEqual(accountBalanceLabel.text, balance)
       }
        
    }
}

```

When I run the test using Product -> Test I get the following error: 

```
2020-04-13 15:45:53.349465-0500 WeatherCucumberSwiftUITests-Runner[40947:2863268] Running tests...
objc[40947]: no class for metaclass 0x600003947ea0

```

**Comment by Tyler-Keith-Thompson** [comment]
Alright, let me try to repro with 11.4. Seems like perhaps the mechanism for allocating XCTestCase classes at runtime is failing in that environment. That's certainly solveable, but I probably can't get you moving today.

**Comment by azamsharp** [comment]
Thats ok! Thanks for your help. I will move to the next BDD tool. I tried most of them and I am not finding any tool that is mature enough to be used.. even for demo purposes.

**Comment by contractor-jim** [comment]
Still think this is one of the easiest tools for BDD on iOS tbh. Has a fix been started? Or shall i fix and send you PR?

**Comment by contractor-jim** [comment]
I found the cause of the issue. When creating the XCTest custom class in TestCaseGenerator the class gets allocated but never registered with the obj-c runtime.

Using 'objc_registerClassPair' works but then any subsequent method additions/injections don't get added as the class is registered first pass through. Just trying to work out a tidy place to register the class / keep a rolling instance and should have a fix.

**Comment by Tyler-Keith-Thompson** [comment]
@contractor-jim I hadn't had time to look into this yet, thank you for grabbing it. Interesting that it suddenly decided registering the class pair was necessary.

**Comment by Tyler-Keith-Thompson** [comment]
CucumberSwift version 2.2.30 should fix the crash you're experiencing. I'll *definitely* be changing the code around this because the fix I wrote is near unreadable, but it does the job and all the tests pass.

I'll leave the issue open for a bit while I refactor and update the documentation to be a little more clear.

**Comment by Tyler-Keith-Thompson** [comment]
Another thanks to @contractor-jim you turned what could've been a multi-day wild goose chase into an afternoon of just fixing the problem.

**Comment by contractor-jim** [comment]
> @contractor-jim I hadn't had time to look into this yet, thank you for grabbing it. Interesting that it suddenly decided registering the class pair was necessary.
Yeah i noticed a lot of things on the projects i am working on / maintain broke with the latest xCode update, seems like they fixed a bunch of stuff.

No thank you for putting this library out there. I love the lib to be honest. BDD on iOS is still missing even after all these years and i tried all the other options out there and none of them work that well. This library is nice and lightweight and does the job.

**Comment by Tyler-Keith-Thompson** [comment]
Refactor is done. Docs have been [updated](https://github.com/Tyler-Keith-Thompson/CucumberSwift/wiki/How-do-i-use-it) to more clearly showcase how to conform to the `StepImplementation` protocol.

I'm going to go ahead and close this, the fix is published and ready to consume.
